### ISSUE TITLE
Need Docker sub-dir with Dockerfile to support `build-microservice.sh -d`

### ISSUE THREAD

**Issue by osowski** [ibm-cloud-architecture/refarch-cloudnative-zipkin#2]
Need basic Dockerfile support, replicating basic Docker build files from other repos.

**Comment by edwinvandegrift** [comment]
Done!

**Comment by osowski** [comment]
https://github.com/ibm-cloud-architecture/refarch-cloudnative-zipkin/commit/11eea60b75654a9a1737e91ce8e711c4eb05ff9b
